### ISSUE TITLE
Create the sidebars

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#7]
Not sure what to put on sidebars but I suggest it should be mostly about the actual shop. Maybe woocommerce widgets with products, not sure what could be done, maybe get an idea with theme demo?

http://fitness.skat.tf/

**Comment by Ganacontrol** [comment]
Another idea for this is social login buttons via plugin shortcode
https://docs.woothemes.com/document/woocommerce-social-login/

Shortcode should be inside there, 
I have no idea if we can make return URL to be the URL where they were before attempting to login.
If not, just redirect to their cart or my account, whatever.
Which reminds me that logged in users should have a My account menu?

**Comment by mj0y** [comment]
"My account" added after "Servicios" for logged-in users. :)
Where should I move it and whats the name in spanish?

**Comment by mj0y** [comment]
Shop page sidebar - Cart / Categories / Top rated products

**Comment by mj0y** [comment]
Is there gonna be a blog menu? What should be in the main sidebar (shown on all pages except woocommerce ones)?

**Comment by Ganacontrol** [comment]
My account should be "Mi Cuenta" and its fine on the menu 

I don't think we will have a blog at all. 
Shop sidebar looks good.

The answer to the main sidebar, I suggest site navigation to the different sections etc like a menu but pretty.

**Comment by mj0y** [comment]
Fixed the my account name.

Check out the sidebar now.... I suggest fuck the site navigation, there already is one in the header?

**Comment by Ganacontrol** [comment]
Lol alright fuck the navigation, use the same sidebar as for woocommerce pages

**Comment by Ganacontrol** [comment]
What about the sidebar for Jessica Chiu? Let's go with the same sidebar for now as shop for now

**Comment by mj0y** [comment]
done?

**Comment by Ganacontrol** [comment]
You missed this one :)
https://suplesmarket.com/wcs3_instructor/jessica-chiu-health-fitness-coach/
